In [7]:
import numpy as np

In [6]:
# ### TODO: Iterate over all elements in the array print the sum using 1 loop

# numpyArray = np.array([1,2,3],
#                       [4,5,6],
#                       [7,8,9])
# # Flatten returns a copy of the array as 1 dimension
# # print(numpyArray.flatten())
# sum = 0
# # nditer iterates over all dimensions of the array 
# for i in np.nditer(numpyArray):
#     sum+=i
# print(sum)


In [12]:
# concatenation in numpy
# what is concatenation
first_array = np.arange(0,3)
second_array = np.arange(9,12)
# lets merge it
conca_array= np.concatenate((first_array,second_array))

array_2d_org = np.arange(0,9).reshape(3,3)
print(f"Array 2d original {array_2d_org}")
# trial 1 adding a row to 2D array
np.concatenate((array_2d_org, second_array.reshape(-1,3)))
# adding row best:
adding_row_vstacked = np.vstack((array_2d_org, second_array))


# adding column
adding_row_hstacked = np.hstack((array_2d_org, second_array.reshape(3,1)))
print(f"Vstacked array: \n {adding_row_vstacked} \n Hstacked array: \n {adding_row_hstacked}")


Array 2d original [[0 1 2]
 [3 4 5]
 [6 7 8]]
Vstacked array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
 Hstacked array: 
 [[ 0  1  2  9]
 [ 3  4  5 10]
 [ 6  7  8 11]]


In [15]:
np_unsorted = np.array([[3,6,1],[2,23,56],[1,45,-1]])
## SORT THE ARRAY --> 3 sorting criterias
## a. sort based on rows
np.sort(np_unsorted, axis =-1)
print(f"sort rows: \n {np.sort(np_unsorted, axis =1)}")

## b. sort based on columns
print(f"sort columns: \n {np.sort(np_unsorted, axis =0)}")
## c. sort all elements
# print(f"sort rows: \n {np.sort(np_unsorted, axis =None).reshape(np_unsorted)}")

sort rows: 
 [[ 1  3  6]
 [ 2 23 56]
 [-1  1 45]]
sort columns: 
 [[ 1  6 -1]
 [ 2 23  1]
 [ 3 45 56]]


In [17]:
import pandas as pd
print(pd.__version__)

2.1.1


In [24]:
pd_series = pd.Series([1,2,3,np.nan])
print(f"Panda Series \n {pd_series}")
## Pandas Date FUnction --> date_range
# it take start, end, frequency/period

start_date = "09/01/2024"
end_date = "09/18/2024"
date_range_periods = pd.date_range(start_date, end_date, periods=5 )
date_range_freq = pd.date_range(start_date, end_date, freq= "3D" )
date_range_freq

Panda Series 
 0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64


DatetimeIndex(['2024-09-01', '2024-09-04', '2024-09-07', '2024-09-10',
               '2024-09-13', '2024-09-16'],
              dtype='datetime64[ns]', freq='3D')

In [26]:
### Pandas dataframe --> tables of rows and columns where each column has a unique datatype
numpy_array_of_fp = [["Strawberrt",5,20],
                      ["Strawberrt",10,100],
                      ["banana",1,200]]
df_from_numpy = pd.DataFrame(numpy_array_of_fp, columns =["Names", "Price", "Quantity"] )
print(df_from_numpy)
python_dict = {"Name": ["Strawberry","Strawberyy","Banana"],
               "Price": [5,10,5],
               "Quantity": [20,100,200]}
df_from_dict = pd.DataFrame(python_dict)
display(df_from_dict)

        Names  Price  Quantity
0  Strawberrt      5        20
1  Strawberrt     10       100
2      banana      1       200


Name  Price  Quantity
0  Strawberry      5        20
1  Strawberyy     10       100
2      Banana      5       200

In [28]:
## Head and tails --> for observing a couple of values
display(df_from_numpy.head(2))
display(df_from_numpy.tail(2))
print(df_from_dict.columns, df_from_dict.index)

Names  Price  Quantity
0  Strawberrt      5        20
1  Strawberrt     10       100

Names  Price  Quantity
1  Strawberrt     10       100
2      banana      1       200

Index(['Name', 'Price', 'Quantity'], dtype='object') RangeIndex(start=0, stop=3, step=1)


In [33]:
df_from_dict_v2 = df_from_dict.copy()
# to_numpy or to_dict will return the format as formatted above
## filtering in pandas
filter_price= df_from_dict_v2["Price"]<10
filter_fp = df_from_dict_v2['Name']=='Strawberry'
df_from_dict_v2 = df_from_dict_v2[filter_price & filter_fp ]
df_from_dict_v2

Name  Price  Quantity
0  Strawberry      5        20

In [35]:
df_from_dict.iloc[[0,1]] #returns indices as if you are accessing numpy array

Name  Price  Quantity
0  Strawberry      5        20
1  Strawberyy     10       100

In [37]:
df_from_numpy_v2 = pd.DataFrame(numpy_array_of_fp,index =[20,30,40], columns =["Names", "Price", "Quantity"] )
df_from_numpy_v2.iloc[[0,1]]

Names  Price  Quantity
20  Strawberrt      5        20
30  Strawberrt     10       100

In [38]:
df_from_numpy_v2.T#transpose array rows <-->columns

20          30      40
Names     Strawberrt  Strawberrt  banana
Price              5          10       1
Quantity          20         100     200

In [40]:
display(df_from_numpy)
display(df_from_numpy_v2.min())# should return minimum of eac column

Names  Price  Quantity
0  Strawberrt      5        20
1  Strawberrt     10       100
2      banana      1       200

Names       Strawberrt
Price                1
Quantity            20
dtype: object

In [41]:
display(df_from_numpy)
display(df_from_numpy_v2.min(), df_from_numpy_v2.max())# should return minimum of eac column

Names  Price  Quantity
0  Strawberrt      5        20
1  Strawberrt     10       100
2      banana      1       200

Names       Strawberrt
Price                1
Quantity            20
dtype: object

Names       banana
Price           10
Quantity       200
dtype: object

In [43]:
# statistical analysis
df_from_numpy_v2.describe() # returns statistical aalysis for numerical columns

Price    Quantity
count   3.000000    3.000000
mean    5.333333  106.666667
std     4.509250   90.184995
min     1.000000   20.000000
25%     3.000000   60.000000
50%     5.000000  100.000000
75%     7.500000  150.000000
max    10.000000  200.000000

In [46]:
df_from_numpy_v2.describe(include="object") # analysis for non-numerical columns
df_from_numpy_v2.describe(include="all") # analysis for all columns

Names      Price    Quantity
count            3   3.000000    3.000000
unique           2        NaN         NaN
top     Strawberrt        NaN         NaN
freq             2        NaN         NaN
mean           NaN   5.333333  106.666667
std            NaN   4.509250   90.184995
min            NaN   1.000000   20.000000
25%            NaN   3.000000   60.000000
50%            NaN   5.000000  100.000000
75%            NaN   7.500000  150.000000
max            NaN  10.000000  200.000000

In [47]:
display(df_from_numpy_v2) # get element with maximum quantity
df_from_numpy_v2.iloc[df_from_numpy_v2['Quantity'].argmax()]

Names  Price  Quantity
20  Strawberrt      5        20
30  Strawberrt     10       100
40      banana      1       200

Names       banana
Price            1
Quantity       200
Name: 40, dtype: object

In [50]:
# combining 2 dataframes together
df_combine = pd.concat([df_from_numpy, df_from_dict]).reset_index(drop=True)
df_combine

Names  Price  Quantity        Name
0  Strawberrt      5        20         NaN
1  Strawberrt     10       100         NaN
2      banana      1       200         NaN
3         NaN      5        20  Strawberry
4         NaN     10       100  Strawberyy
5         NaN      5       200      Banana

In [52]:
df_combine.groupby(["Name"]).apply(print)


  Names  Price  Quantity    Name
5   NaN      5       200  Banana
  Names  Price  Quantity        Name
3   NaN      5        20  Strawberry
  Names  Price  Quantity        Name
4   NaN     10       100  Strawberyy


Empty DataFrame
Columns: []
Index: []