## PROG8245 Assignment 1: (Total Marks 100)
## Start on 16th of September- Due on 27th of September

- TODO: write your name and ID below
- Name: Jaiv Burman
- ID: 8930180
- Kindly note that this assignment is to be solved by yourself, without the use of AI and chatbots.
- If chatbot usage is detected, the penalty that is discussed in Week 1 slides will apply.
- Each code block will have a Todo comment which explains the functionality, expected input, and expected output of the function.
- There are 10 marks in this assignment for assuring that the code couldn't be broken (no errors can be thrown, please consider mathematical and logical errors)
- There are 10 marks in this assignment for commenting and code readability.


### Part 1: Python Basics

#### Question 1:

In [4]:
price = float(input("Enter the price of an item: ")) # to take price as an input
tax = 0.13 # which is 13%
def total_price(price, tax):
    # 3 marks
    # TODO: write the functionality of the code where
    #  you are taking as an input a price of an item and the
    #  tax in decimal (13% tax will be given as 0.13),
    #  you should return the taxedPrice of that item
    #  which will be the total price after tax a customer must pay
    # (The price of the item plus the applicable taxes)
    taxedPrice = price - (price * tax)
    return taxedPrice

print(f"The price of the item plus the applicable taxes is: {total_price(price, tax)}")


The price of the item plus the applicable taxes is: 87.0


#### Question 2:

In [5]:
def divisible_by(x, y):
    # 3 marks
    # TODO: write a function that returns True if x is divisible by y,
    #  and returns False OTHERWISE (all other cases).
    if y==0:
        return False
    
    return x%y ==0

x= int(input(" Enter the 1st number: "))
y= int(input(" Enter the 2nd number: "))

print(f"for {x} & {y} as {x}/{y}:")
divisible_by(x,y)

for 4 & 2 as 4/2:


True

#### Question 3:

In [10]:
def basic_calculator(x, y, operator):
    try:
        if operator == '+':
            result = x + y
        elif operator == '-':
            result = x - y
        elif operator == '*':
            result = x * y
        elif operator == '/':
            if y == 0:
                return "error"
            result = x / y
        elif operator == '%':
            if y == 0:
                return "error"
            result = x % y
        elif operator == '//':
            if y == 0:
                return "error"
            result = x // y
        else:
            return "invalid"
        
        return result
    except Exception as e:
        return "error"
x= int(input(" Enter the 1st number: "))
y= int(input(" Enter the 2nd number: "))
operator  = input(" Enter the operator (+, -, *, /, %, //): ")    

basic_calculator(x,y,operator)

    # 5 marks
    # TODO: write the functionality of the code where you are
    #  coding a basic calculator that performs basic addition "+", subtraction "-",
    #  multiplication "*", division "/", modulus "%" and integer division "//"
    #  the function must apply the operator to x and y for example:
    #  basicCalculator(10, 15, "*") should apply 10*15 and save it to the result variable
    #  NOTE: YOU NEED TO HANDLE DIVISION ERRORS BY RETURNING A STRING WITH THE WORD "error"
    #  NOTE: YOU NEED TO HANDLE AN INVALID OPERATOR BY RETURNING A STRING HAVING THE WORD "invalid"

'invalid'

#### Question 4:

In [9]:
        
def sum_of_even(numbers_list):
    # 3 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a list of numbers
    # returning the sum of even numbers in the list
    # NOTE: YOU NEED TO HANDLE ERRORS OF GIVING LIST OF STRINGS OR/AND
    #  STRINGS WITH NUMBERS by returning "invalid"
    # sum_of_even([1,2,3,4,5,6]) = 12
    sum = 0
    
    for num in numbers_list:
        if num % 2 == 0:     #checking for even
            sum += num
    return sum #return sum of even numbers

numbers_list= [] # initialized list

# Now lets take the list of numbers as input and checking for validation for it should be number not string or a number with string
while True:
    try:
        n= int(input("How many numbers you would like to enter: "))
        if n<=0:
            raise ValueError("The number must be greater than zero.") # we checking for positive numbers
        break # or else it is valid for positive
    except ValueError:
        print("invalid") # anything other than positive integer throw as "invalid"
        
        
# For input
for i in range(n):
    while True:
        try:
            numbers = int(input(f"Enter number {i+1}: "))
            numbers_list.append(numbers)  # appending the numbers to the list
            break       #if anything is invalid then exit the loop
        except ValueError:
            print("invalid") # anything other than positive integer throw as "invalid"

sum_of_even(numbers_list)

invalid
invalid
invalid
invalid
invalid
invalid
invalid
invalid
invalid
invalid
invalid
invalid
invalid


6

#### Question 5:

In [14]:
def reverse_string(input_string):
    reverse_string = input_string[::-1]
    # 3 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a string
    # returns the reverse of the string
    # reverse_string("hello") = "olleh"
    # NOTE: Numbers should be handled as strings ex: 123 returns "321"
    return ""

input_string = input("Enter the string: ")     
#we don't need to check for numbers as string because python for default takes as any input as string 

reverse_string(input_string)


'o321leh'

#### Question 6:

In [10]:
def diamond_string(length):
    # 5 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a POSITIVE ODD length
    # saves in a string the diamond as follows:
    # diamond_string(5)
    #   *
    #  ***
    # *****
    #  ***
    #   *
    # NOTE: The input must be positive odd, if not return empty string ""   
    if length <=0 or length % 2 ==0:
        return "" # invalid input gives empty string
    
    mid = length //2     #calculating  centre index because it will get used as space filling in the pattern
    diamond = ""
                                #taking an assumption for lenght = 9
    for i in range(mid + 1):         #making upper part of diamond upto the number of length
        gap = " " * (mid - i)       #for space where it will get reduced for every range
        stars = "*" * (2 * i + 1)      #to display odd number of stars for symmetry
        diamond += gap + stars + "\n"   #appending to the empty string
        
    for i in range(mid - 1, -1, -1):    # similar loop function but starting middle length and go reverse
        gap = " " * (mid - i)
        stars = "*" * (2 * i + 1)
        diamond += gap + stars + "\n"
    
    return diamond

# length = 9
while True:
    try:
        n= int(input("How many numbers you would like to enter: "))
        if n<=0 or n%2 == 0:
            print("")# we checking for positive numbers
        else:
            print(diamond_string(n))# or else it is valid for positive
            break
    except ValueError:
        print("invalid") # anything other than positive integer throw as "invalid"
          # prints:   *



invalid
invalid
  *
 ***
*****
 ***
  *



#### Question 7:

In [22]:


def longest_consecutive_subarray(number_array):
    # 8 marks
    # TODO: write the functionality of the code where you are
    # taking as an input an array of REAL NUMBERS
    # return the length of the longest subarray that could be
    # built using the input
    # longest_consecutive_subarray([100, 4, 200, 1, 3, 2]) = 4
    # Function should return 4 which represents in this case
    # the longest_consecutive_subarray that could be built [1,2,3,4]
    # You can't use Built in Sorting!
    # Note: - If any error exists in the input, "error" should be returned
    #       - The difference between any 2 consecuetive numbers is 1    
    set_of_num = set(number_array)      #converting into a set since it will take a repeated value willnbe stored once and make a set of unique elements
    max_l = 0       # t track the length of consecutive array
    
    for num in set_of_num:      
        if num - 1 not in set_of_num:       # looping through every element 
            present_num = num
            count = 1
            
            while present_num + 1 in set_of_num:
                present_num += 1
                count += 1
                
            max_l = max(max_l, count)
    
    return max_l

input_arr = input("enter array and separate it by space: ")

try:
    actual_arr_n_space = [float(num) for num in input_arr.split()]
    result = longest_consecutive_subarray(actual_arr_n_space)
    print(result)
except ValueError:
    print("error")
    


5


#### Question 8 (Challenging):

In [100]:
def can_be_segmented(input_string, word_dict):
    # 15 marks
    # TODO: Write the functionality of the code where you
    # are given as an input a string and a word_dict
    # Your target is to return True, if input_string can be segmented
    # (broken-down) into a sequence of one or more dictionary words
    # otherwise return False
    # Sample Input: can_be_segmented("applepenapple", {'apple','pen'}) ==> True
    # Sample Input: can_be_segmented("catsandog", {'cats','dog','sand','and','cat'}) ==> False
    # Hint: You can start by checking which prefix exist in the dictionary, and call the same function recursively
    # on the remaining string.
    
    for x in word_dict :
        if(input_string.find(x)>=0):
            input_string = input_string.replace(x, '')
        else:
            return False
    return True

input_string = input("input a string")
word_dic_input = input("words to be compared in dictionary and separate it by spaces: ")
word_dict = set(word_dic_input.split())

print(input_string)
print(word_dict)
print(can_be_segmented(input_string, word_dict))


catsandog
{'sand', 'cats', 'dog'}
False


### Part 2: Numpy Basics: 
- In this Part of the assignment, you are <b>ONLY ALLOWED</b> to use Numpy and its functions. 
- You are not expected to use Loops.

In [24]:
import numpy as np

#### Question 9:

In [99]:
def no_zeros(array_input):
    # 3 marks
    ## TODO: This function should return True if 
    ## numpy array arrayInput does not contain any zero
    ## and will return False otherwise.
    ## Implement this function using ONLY numpy methods
    ## Sample input: np.array([1,2,3,4,5,6,0]) Sample Output: False
    ## Sample input: np.array([1,2,3,4,5,6]) Sample Output: True
  return not np.any(array_input == 0)


my_input = input("Enter number by space: ")

array_input = np.array([int(x) for x in my_input.split()])
print(my_input)
print(no_zeros(array_input))


23 34 22 0 13 4 4 
False


#### Question 10:

In [70]:
def two_dimensions(n):
    # 7 marks
    ## TODO: This function should create a 2d Array of shape n*n for any positive number
    ## Where the borders of the array are ones
    ## all other elements are zero
    ## Implement this function using ONLY numpy methods
    ## Sample input 3
    ## sample output [[1,1,1],[1,0,1],[1,1,1]]
    array = np.ones((n,n), dtype= int)
    array[1:-1,1:-1 ]= 0        #selecting 1st row and column , last row & column and setting as "0"
    return array

n =  int(input("Enter number of dimension: "))
print(two_dimensions(n))
    

[[1 1 1]
 [1 0 1]
 [1 1 1]]


#### Question 11:

In [96]:
def random_generation(n,min,max):
    # 5 marks
    # TODO: Write a function that takes as an input
    # Dimension of 2d Array n, min and max
    # Generate an n*n array with random numbers between
    # min and max inclusive
    # Such that no element is duplicated
    # return numpy array
    # Implement this function using ONLY numpy methods
    # Sample Input: random_generation(3,0,12) --> [[4,2,6],[1,5,11],[10, 3,9]]
    num = np.random.choice(np.arange(min,max +1), (n*n), replace= False)   
    return num.reshape((n,n))
try:
    n = int(input("enter shape of array: "))
    min = int(input("enter its minimum value: "))
    max = int(input("enter its maximum value: "))

    if (max-min+1)< (n*n):
        print("Error: Not enough unique values to fill the array")
    else:
        arr = random_generation(n,min,max)
        print(arr)
        
except ValueError:
    print("Invalid")
    


[[7 1 8]
 [5 4 3]
 [6 9 2]]


#### Question 12:

In [95]:
def matrix_border_sum(matrix):
    # 8 marks
    # TODO: Write a function that takes as an input a matrix
    # and return the sum of all elements in the borders
    # Implement this function using ONLY numpy methods
    # Sample Input: np.array([[1,2,3],
    #                         [4,5,6],
    #                         [7,8,9]])
    # Output: matrix_border_sum(matrix) =  1+2+3+4+6+7+8+9 = 40
    # if not isinstance(matrix, np.ndarray):
    #     raise ValueError("Input should be a NumPy array.")
    
    top = matrix[0, :]
    bottom = matrix[-1, : ]
    left = matrix[1:-1, 0 ]
    right = matrix[1:-1, -1]
    
    border= np.concatenate((top, bottom, left, right))
    
    return np.sum(border)

try:    
    matrix = input("Enter matrix in a list:")
    matrix = np.array(eval(matrix))         # convert the given list in the context of arrays
    print(matrix)
    result= matrix_border_sum(matrix)
    print(result)
except ValueError:
    print("Error:")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
40


### Part 3: Pandas

In [88]:
import pandas as pd

#### Question 13 (12 marks): 
- Using RegularSeasonCompactResults.csv and Teams.csv apply the following functionalities

In [90]:
# Using RegularSeasonCompactResults.csv
# 1- Create a filter to show if there are any draw matches
# 2- Apply the filter to the dataframe
# 3- SHOW/PRINT the dataframe length or count (4 marks)
## TODO: Your code should be here
season = pd.read_csv("./RegularSeasonCompactResults.csv")

draw = season["Wscore"] == season["Lscore"]
print({len(season[draw])})

{0}


In [92]:
# Using RegularSeasonCompactResults.csv
# 1- Create a filter showing the entries where the winningteamID= 1400- (last two digits of your id)
# 2- Create another filter for the season of 2013
# 3- Apply the filter to the dataframe
# 4- Show the resulted dataframe (4 marks)
# (Example: IF your id is 8000021, the winning team id = 1400-21= 1379)
# TODO: Your code should be here

winningteamID = season["Wteam"] == (1400-80)
season_2013 = season["Season"] == 2013
season_filtered = season[(winningteamID) & (season_2013)]
print(season_filtered)

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
124150    2013       9   1320      84   1405      81    H      1
124298    2013      12   1320      72   1315      47    H      0
124936    2013      26   1320      72   1454      61    H      0
125088    2013      30   1320      76   1294      59    H      0
125198    2013      33   1320      82   1206      77    A      1
125651    2013      47   1320      82   1388      75    H      0
126115    2013      61   1320      70   1229      60    A      0
126433    2013      68   1320      84   1133      53    H      0
126825    2013      76   1320      85   1179      55    H      0
126897    2013      79   1320      58   1356      45    H      0
127409    2013      89   1320      57   1455      52    H      0
127499    2013      92   1320      48   1283      37    H      0
127786    2013      97   1320      68   1133      65    A      0
127862    2013     100   1320      61   1166      54    H      0
128044    2013     103   

In [94]:
# Using RegularSeasonCompactResults.csv & Teams.csv
# 1- Load and merge both dataframes
# 2- Where the merge is on WinningTeamId (RegularSeasonCompactResults) and TeamId (Teams.csv)
# 3- Name the dataframe: DFCombined
# 4- Show the top 3 rows (4 marks)
# TODO: Your code should be here
team = pd.read_csv("./Teams.csv")
merge = pd.merge(season, team, left_on="Wteam", right_on="Team_Id", how='inner')
merge


Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot  Team_Id  \
0         1985      20   1228      81   1328      64    N      0     1228   
1         1985      25   1106      77   1354      70    H      0     1106   
2         1985      25   1112      63   1223      56    H      0     1112   
3         1985      25   1165      70   1432      54    H      0     1165   
4         1985      25   1192      86   1447      74    H      0     1192   
...        ...     ...    ...     ...    ...     ...  ...    ...      ...   
145284    2016     132   1114      70   1419      50    N      0     1114   
145285    2016     132   1163      72   1272      58    N      0     1163   
145286    2016     132   1246      82   1401      77    N      1     1246   
145287    2016     132   1277      66   1345      62    N      0     1277   
145288    2016     132   1386      87   1433      74    N      0     1386   

              Team_Name  
0              Illinois  
1            Alabama St  
2               Arizona  
3               Cornell  
4           F Dickinson  
...                 ...  
145284  Ark Little Rock  
145285      Connecticut  
145286         Kentucky  
145287      Michigan St  
145288   St Joseph's PA  

[145289 rows x 10 columns]